"""AI Insights Section - Generates HTML for AI-generated observations."""

from typing import Dict, Any, List, Optional


class AISection:
    """Generates AI insights HTML section."""
    
    def generate(self, insights_data: Dict[str, Any]) -> str:
        """
        Generate AI insights HTML.
        
        Args:
            insights_data: Dict containing:
                - insights: list of str (numbered insights)
                - model: str - AI model used
                - timestamp: str - when generated
        
        Returns:
            HTML string for AI insights section
        """
        if not insights_data or not insights_data.get("insights"):
            return ""
        
        insights = insights_data["insights"]
        model = insights_data.get("model", "AI Model")
        
        html = f"""
        <div class="card">
            <div class="card-header">
                <h2>🤖 AI Observations</h2>
                <p style="color: #666; font-size: 0.9rem; margin-top: 0.5rem;">
                    Analyst-style findings generated by {model}
                </p>
            </div>
            <div class="card-body">
        """
        
        # Format insights as numbered list
        if isinstance(insights, list):
            html += "<ol style='line-height: 1.8; padding-left: 1.5rem;'>"
            
            for insight in insights[:7]:  # Limit to 7 insights
                # Clean up insight text
                clean_insight = str(insight).strip()
                
                # Remove number if AI already added it
                if clean_insight and clean_insight[0].isdigit() and '. ' in clean_insight[:4]:
                    clean_insight = clean_insight.split('. ', 1)[1]
                
                html += f"<li style='margin-bottom: 1rem; color: #333;'>{clean_insight}</li>"
            
            html += "</ol>"
        
        elif isinstance(insights, str):
            # Handle string format (fallback)
            html += f"<div style='white-space: pre-wrap; line-height: 1.6;'>{insights}</div>"
        
        html += """
            </div>
        </div>
        """
        
        return html
